name: stytra
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  # GUI
  - pyqt=5.15.*
  - pyqtgraph=0.13.*
  - qdarkstyle=2.7
  - qimage2ndarray=1.10.*

  # numerical stack
  - numpy=1.23.5
  - scipy=1.10.*
  - numba=0.57.*
  - pandas=1.5.*

  # image and video
  - scikit-image=0.20.*
  - pillow=9.5.*
  - imageio=2.31.*
  - imageio-ffmpeg=0.4.*
  - opencv=4.8.*

  # data, versioning, hardware
  - pytables=3.8.*
  - pyfirmata=1.1.*

  # misc stytra dependencies
  - anytree=2.8.*
  - pims=0.6.*
  - colorspacious=1.1.*

  # optional but useful for Stytra video recording/offline video
  - av=10.*
  - ffmpeg=6.*

  - pip:
      - flammkuchen==1.0.3
      - arrayqueues==1.4.1
      - "lightparam>=0.4,<0.5"
